var places = ["Fance", "Australia", "USA", "UK", "Singapore", "Canada"];
console.log("Orignal Order");
console.log(places);
console.log("Alphabetical Order");
var sort_places = ["Fance", "Australia", "USA", "UK", "Singapore", "Canada"];
sort_places.sort();
console.log(sort_places);
console.log("Orignal order");
console.log(places);
console.log("Reverse Order");
var reverse_string = places.slice().reverse();
console.log(reverse_string);
console.log("Orignal Order");
console.log(places);
var reverse_alphabetical = places.slice().sort(function (a, b) { return b.localeCompare(a); });
console.log("Reverse Alphabetical Order");
console.log(reverse_alphabetical);
console.log("Orignal Array");
console.log(places);
