"use strict";
var guest_list = ['Afzal', 'Nouman', 'Maqsood', 'Wajahat'];
var guest_name = guest_list[0];
console.log(guest_name + " Kindly come to dinner till 10 PM.");
guest_name = guest_list[1];
console.log(guest_name + " Kindly meet me for the dinner tommorow");
guest_name = guest_list[2];
console.log(guest_name + " Kindly meet us at dinner on Friday. ");
guest_name = guest_list[3];
console.log(guest_name + " Kindly arrange Bottles for the dinner tonight.");
