"use strict";
let Ar2 = ['Fahad', 'Safdar', 'Akhter', 'Ali'];
let msg1 = "Mr, " + Ar2[0];
console.log(msg1);
msg1 = "Mr, " + Ar2[1];
console.log(msg1);
msg1 = "Mr, " + Ar2[2];
console.log(msg1);
msg1 = "Mr, " + Ar2[3];
console.log(msg1);
